spring.application.name=ateion-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ateion_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.com.ateion.backend=INFO

server.error.include-message=never
server.error.include-binding-errors=never
